### ISSUE TITLE
The result will not be output?

### ISSUE THREAD

**Issue by badboycxcc** [hdks-bug/hermit#3]
I execute whoami, how to view the return results

<img width="862" alt="截屏2024-04-20 上午11 40 59" src="https://github.com/hideckies/hermit/assets/72059221/3ef8c056-97dd-49ba-8b29-c1da2aba6118">

**Comment by hdks-bug** [comment]
@badboycxcc 
You can get results with `loot show` command.  Or I'll add `task results` command in the next update.
