### ISSUE TITLE
Donut + ScareCrow + Nimcrypt2 Support ?

### ISSUE THREAD

**Issue by RajChowdhury240** [hdks-bug/hermit#8]
- https://github.com/icyguider/Nimcrypt2
- https://github.com/optiv/ScareCrow
- https://github.com/TheWover/donut

**Comment by hdks-bug** [comment]
@Rajchowdhury420 
Very interesting, but there are currently no plans for support. If I (we) were to do it, I might make it into a plugin feature or something. Suggestions are welcome.
